version: '3'
networks:
  my-network:
    driver: bridge
services:
  web-api:
    image: ricardogaefke/ricardogaefke-www:www_site
    container_name: web-api
    networks:
      - my-network
  nginx:
    image: ricardogaefke/ricardogaefke-www:www_nginx
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    networks:
      - my-network
